# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build and Lint
        run: npm run pretest
      - name: Run tests
        run: xvfb-run -a npm test

  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm audit --audit-level moderate
